### PR TITLE
lab homepage

### PR DESCRIPTION
**Pull request by deep-j**

### CODE REVIEW

**Comment by Rahul-RB** [comment]
Hi, thank you for lodging the PR. I'd like you to restructure the files according to this pattern. Do the following steps. Don't close this PR.

Step 1:
-
- Create a folder named `Lab` in:
    - `Templates folder` : `hawkeye/hawkeye/templates` 
    - `Static - CSS folder` : `hawkeye/hawkeye/static/css` 
    - `Static - JS folder` : `hawkeye/hawkeye/static/js` 

Step 2:
-
- Then do the following:
    - Place any `*.html` into the `Templates folder`.
    - Place any `*.css` into the `Static - CSS folder`.
    - Place any `*.html` into the `Static - JS folder`. 

Step 3:
-
- After creating the folders and placing the files, do the following:
    - `git add .`
    - `git commit -m "Restructured files as requested in PR #24 "
 
Step 4:
-
- Refresh this page. Comment on this PR (#24 ) once you're done.

**Comment by Rahul-RB** [comment]
Could you please place the `*.html` files into `hawkeye/hawkeye/templates`. Don't worry about linking CSS and JS files within that, I'll handle the links, just placing the file there is fine :+1:

**Comment by deep-j** [comment]
Updated the files.

**Comment by Rahul-RB** [comment]
Cool,
Thank you! :tada:

**Pull request merged**
